name: Build App Vue

on:
  pull_request:
    branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        
        - name: Install Dependencies
          run: npm ci

        - name: Run Build
          run: npm run build



  